#!/usr/bin/python

#
# Writes the list archive search page (http://mail.gnome.org/archives/)
#
# Man, this'd be better off as a python script
#

import sys
import re
import time
from types import TupleType

sys.path.append('/usr/lib/mailman/bin')

import paths
from Mailman import mm_cfg
from Mailman import MailList
from Mailman import Utils
from Mailman import Errors
from Mailman.i18n import _


dirname = "/var/lib/mailman/archives/public"
NAMAZU_HEAD = "/home/admin/namazu/public-templates/NMZ.head"

# hack
names = Utils.list_names()
names.sort()

vhost='gnome.org'

mlists = []
for n in names:
    mlist = MailList.MailList(n, lock=0)
    if not mlist.advertised:
        continue

    if not mlist.archive or mlist.archive_private:
        continue

    if vhost and mm_cfg.VIRTUAL_HOST_OVERVIEW and \
           vhost.find(mlist.web_page_url) == -1 and \
           mlist.web_page_url.find(vhost) == -1:
        continue
    mlists.append(mlist)

def write_form(INDEX, lists):

    print >>INDEX, """
<form method="get" action="/mailman/search">
<p>
<strong>Search String:</strong> 
<input type="text" name="query" size="40"/>
<input type="submit" name="submit" value="Search!"/>
<!-- <input type="hidden" name="idxname" value="foobar"> -->
<a href="/mailman/search">[How to search]</a>
</p>
<p>
<strong>List:</strong>
<select name="subquery"> 
 <option value="">All mailing lists</option>"""

    for list in lists:
	print >>INDEX, '<option value="+uri:/^http://mail.gnome.org/archives/%s/">%s</option>' % (list.internal_name(), list.real_name)


    print >>INDEX, """
</select>
<input type="hidden" name="reference" value="off"/>
</p>
<p>
<strong>Display:</strong>
<select name="max">
<option value="10">10</option>
<option selected="selected" value="20">20</option>
<option value="30">30</option>
<option value="50">50</option>
<option value="100">100</option>
</select>
<strong>Description:</strong>
<select name="result">
<option selected="selected" value="normal">normal</option>
<option value="short">short</option>
</select>
<strong>Sort:</strong>
<select name="sort">
<option selected="selected" value="score">by score</option>
<option value="date:late">by date in late order</option>
<option value="date:early">by date in early order</option>
<option value="field:subject:ascending">by title in ascending order</option>
<option value="field:subject:descending">by title in descending order</option>
<option value="field:from:ascending">by author in ascending order</option>
<option value="field:from:descending">by author in descending order</option>
<option value="field:size:ascending">by size in descending order</option>
<option value="field:size:descending">by size in descending order</option>
<option value="field:uri:ascending">by URI in descending order</option>
<option value="field:uri:descending">by URI in descending order</option>
</select>
</p>
</form>
"""


INDEX=open("%s/index.html" % dirname, "w")

print >>INDEX, """<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <link href="/css/layout.css" rel="stylesheet" type="text/css" media="screen">
  <link href="/css/style.css" rel="stylesheet" type="text/css" media="all">
  <link rel="icon" type="image/png" href="http://www.gnome.org/img/logo/foot-16.png">
  <link rel="SHORTCUT ICON" type="image/png" href="http://www.gnome.org/img/logo/foot-16.png">
  <title>GNOME Mail Services</title>
  <base href="http://mail.gnome.org/" />
</head>

<body>
  <!-- site header -->
  <div id="page">
    <ul id="general">
      <li id="siteaction-gnome_home" class="home">
        <a href="http://www.gnome.org/" title="Home">Home</a>
      </li>
      <li id="siteaction-gnome_news">
        <a href="http://news.gnome.org" title="News">News</a>
      </li>
      <li id="siteaction-gnome_projects">
        <a href="http://www.gnome.org/projects/" title="Projects">Projects</a>
      </li>
      <li id="siteaction-gnome_art">
        <a href="http://art.gnome.org" title="Art">Art</a>
      </li>
      <li id="siteaction-gnome_support">
        <a href="http://www.gnome.org/support/" title="Support">Support</a>
      </li>
      <li id="siteaction-gnome_development">
        <a href="http://developer.gnome.org" title="Development">Development</a>
      </li>
      <li id="siteaction-gnome_community">
        <a href="http://www.gnome.org/community/" title="Community">Community</a>
      </li>
    </ul>
    <div id="header">
      <h1>
	GTK+ and GNOME Mailing Lists
      </h1>
      <div id="tabs">
        <ul id="portal-globalnav">
          <li id="portaltab-root" class="selected">
            <a href="/"><span>Home</span></a>
          </li>
          <li><a href="/mailman/listinfo"><span>Mailing lists</span></a></li>
          <li class="selected"><a href="/archives"><span>List archives</span></a></li>
        </ul>
      </div> <!-- end of #tabs -->
    </div> <!-- end of #header -->
  </div>
<!-- end site header -->

  <div class="body">
    <div id="content">

<p><b>NOTICE (2006-07-08):</b> We're re-building the archive search indexes (again). It bombed out silently last time leaving lockfiles in place (and archives unsearchable). Please bear with us while we try to get it sorted out. -- GNOME sysadmin team.</p>"""

write_form(INDEX, mlists)

print >>INDEX, """  
    <hr/>
    <ul style="-moz-column-width: 45ex; -webkit-column-width: 45ex; column-width: 45ex">
"""

for list in mlists:
    print >>INDEX, '<li><a href="%s/">%s</a></li>' % (list.internal_name(), list.real_name)


print >>INDEX, """  </div> <!-- end of content -->

  <div id="footer">
    Copyright &copy; 2005, 2006, 2007 <a href="http://www.gnome.org/">The GNOME Project</a>.<br />
    <a href="http://validator.w3.org/check/referer">Optimised</a> for <a href="http://www.w3.org/">standards</a>. Hosted by <a href="http://www.redhat.com/">Red Hat</a>.
  </div>

  </div> <!-- end of div.body -->
</body>
</html>"""
    
INDEX.close()

INDEX=open(NAMAZU_HEAD, "w")

print >>INDEX, """
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN"
        "http://www.w3.org/TR/REC-html40/strict.dtd">
<html>
<!--

     autogenerated by /home/admin/mhonarc/update-master
     DO *NOT* EDIT! Run the above instead.

-->
<head>
<!-- LINK-REV-MADE -->
<link rev=made href="mailto:support@gnome.org">
<!-- LINK-REV-MADE -->
<title>Search mail.gnome.org</title>
<style type="text/css"><!--
  strong.keyword { color: Red; }
  p.example      { text-indent: 1em; 
                   color: Navy;
		   font-weight: bold;
                   font-family: monospace; }
  code           { color: Navy;
                   font-family: monospace; }
  code.example   { color: Navy;
		   font-weight: bold;
                   font-family: monospace; }
  code.operator  { color: Navy;
                   font-family: monospace; 
		   font-weight: bold; }
--></style>
</head>
<body>
<h1>Search mail.gnome.org</h1>

<p><b>NOTICE (2006-07-08):</b> We're re-building the archive search indexes (again). It bombed out silently last time leaving lockfiles in place (and archives unsearchable). Please bear with us while we try to get it sorted out. -- GNOME sysadmin team.</p>

<p>
This index contains <!-- FILE --> lots of <!-- FILE --> documents and
<!-- KEY --> lots of <!-- KEY --> keywords. 
</p>
<p>
<strong>Last modified: <!-- DATE --> 2006-07-08 <!-- DATE --></strong>
</p>
<hr/>"""

write_form(INDEX, mlists)
INDEX.close()


