#!/usr/bin/python

#
# Writes the list archive search page (http://mail.gnome.org/archives/)
#
# Man, this'd be better off as a python script
#

import sys
import re
import time
from types import TupleType

sys.path.append('/usr/lib/mailman/bin')

import paths
from Mailman import mm_cfg
from Mailman import MailList
from Mailman import Utils
from Mailman import Errors
from Mailman.i18n import _
import glob
import os.path


dirname = "/var/lib/mailman/archives/public"

# hack
names = Utils.list_names()
names.sort()

vhost='gnome.org'

mlists = []
all_mlists = set()
for n in names:
    mlist = MailList.MailList(n, lock=0)
    all_mlists.add(mlist.internal_name())
    if not mlist.advertised:
        continue

    if not mlist.archive or mlist.archive_private:
        continue

    if vhost and mm_cfg.VIRTUAL_HOST_OVERVIEW and \
           vhost.find(mlist.web_page_url) == -1 and \
           mlist.web_page_url.find(vhost) == -1:
        continue
    mlists.append(mlist)

archived_lists = set([os.path.basename(path) for path in glob.glob(os.path.join(dirname, '*')) if os.path.islink(path)])
obsolete_mlists = archived_lists - all_mlists


INDEX=open("%s/index.html" % dirname, "w")

print >>INDEX, """<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <link href="/css/layout.css" rel="stylesheet" type="text/css" media="screen">
  <link href="/css/style.css" rel="stylesheet" type="text/css" media="all">
  <link rel="icon" type="image/png" href="http://www.gnome.org/img/logo/foot-16.png">
  <link rel="SHORTCUT ICON" type="image/png" href="http://www.gnome.org/img/logo/foot-16.png">
  <title>GNOME Mail Services</title>
</head>

<body>
  <!-- site header -->
  <div id="page">
    <ul id="general">
      <li id="siteaction-gnome_home" class="home">
        <a href="http://www.gnome.org/" title="Home">Home</a>
      </li>
      <li id="siteaction-gnome_news">
        <a href="http://news.gnome.org" title="News">News</a>
      </li>
      <li id="siteaction-gnome_projects">
        <a href="http://www.gnome.org/projects/" title="Projects">Projects</a>
      </li>
      <li id="siteaction-gnome_art">
        <a href="http://art.gnome.org" title="Art">Art</a>
      </li>
      <li id="siteaction-gnome_support">
        <a href="http://www.gnome.org/support/" title="Support">Support</a>
      </li>
      <li id="siteaction-gnome_development">
        <a href="http://developer.gnome.org" title="Development">Development</a>
      </li>
      <li id="siteaction-gnome_community">
        <a href="http://www.gnome.org/community/" title="Community">Community</a>
      </li>
    </ul>
    <div id="header">
      <h1>
	GTK+ and GNOME Mailing Lists
      </h1>
      <div id="control">
      <div id="search">
        <form method="get" action="http://www.google.com/custom">
          <input type="text" name="q" maxlength="255" size="15" class="searchTerms">
          <input type="hidden" name="domains" value="mail.gnome.org">
          <select name="hq">
            <option value="inurl:/archives/">All mailing lists</option>"""

for list in mlists:
    print >>INDEX, '<option value="inurl:/archives/%s/">%s</option>' % (list.internal_name(), list.internal_name())


print >>INDEX, """
            </select>
            <input type="hidden" name="sitesearch" value="mail.gnome.org">
            <input type="submit" class="searchButton" value="Search">
          </form>
        </div>
      </div>
      <div id="tabs">
        <ul id="portal-globalnav">
          <li id="portaltab-root">
            <a href="/"><span>Home</span></a>
          </li>
          <li><a href="/mailman/listinfo"><span>Mailing lists</span></a></li>
          <li class="selected"><a href="/archives"><span>List archives</span></a></li>
        </ul>
      </div> <!-- end of #tabs -->
    </div> <!-- end of #header -->
  </div>
<!-- end site header -->

  <div class="body">

    <ul style="-moz-column-width: 30ex; -webkit-column-width: 30ex; column-width: 30ex">
"""

for list in mlists:
    print >>INDEX, '<li><a href="%s/">%s</a></li>' % (list.internal_name(), list.internal_name())
print >>INDEX, "</ul>"

if len(obsolete_mlists):
    print >>INDEX, """Obsolete mailing lists:
    <ul style="-moz-column-width: 30ex; -webkit-column-width: 30ex; column-width: 30ex">"""

    for list in sorted(obsolete_mlists):
        print >>INDEX, '<li><a href="%s/">%s</a></li>' % (list, list)
    
    print >>INDEX, "</ul>"

print >>INDEX, """

  <div id="footer">
    Copyright &copy; 2005, 2006, 2007 <a href="http://www.gnome.org/">The GNOME Project</a>.<br />
    <a href="http://validator.w3.org/check/referer">Optimised</a> for <a href="http://www.w3.org/">standards</a>. Hosted by <a href="http://www.redhat.com/">Red Hat</a>.
  </div>

  </div> <!-- end of div.body -->
</body>
</html>"""
    
INDEX.close()

