#!/usr/bin/perl -w

#
# Writes the list archive search page (http://mail.gnome.org/archives/)
#
# Man, this'd be better off as a python script
#

$dirname = "/var/lib/mailman/archives/public";
$NAMAZU_HEAD = "/home/admin/namazu/public-templates/NMZ.head"; 

sub write_form {
    my ($dirs) = shift;

    print INDEX <<EOT;
<form method="get" action="/mailman/search">
<p>
<strong>Search String:</strong> 
<input type="text" name="query" size="40"/>
<input type="submit" name="submit" value="Search!"/>
<!-- <input type="hidden" name="idxname" value="foobar"> -->
<a href="/mailman/search">[How to search]</a>
</p>
<p>
<strong>List:</strong>
<select name="subquery"> 
 <option value="">All mailing lists</option>
EOT

    for $dir (@$dirs) {
	print INDEX <<EOT
 <option value="+uri:/^http://mail.gnome.org/archives/$dir/">$dir</option>
EOT
    }

  print INDEX <<EOT;
</select>
<input type="hidden" name="reference" value="off"/>
</p>
<p>
<strong>Display:</strong>
<select name="max">
<option value="10">10</option>
<option selected="selected" value="20">20</option>
<option value="30">30</option>
<option value="50">50</option>
<option value="100">100</option>
</select>
<strong>Description:</strong>
<select name="result">
<option selected="selected" value="normal">normal</option>
<option value="short">short</option>
</select>
<strong>Sort:</strong>
<select name="sort">
<option selected="selected" value="score">by score</option>
<option value="date:late">by date in late order</option>
<option value="date:early">by date in early order</option>
<option value="field:subject:ascending">by title in ascending order</option>
<option value="field:subject:descending">by title in descending order</option>
<option value="field:from:ascending">by author in ascending order</option>
<option value="field:from:descending">by author in descending order</option>
<option value="field:size:ascending">by size in descending order</option>
<option value="field:size:descending">by size in descending order</option>
<option value="field:uri:ascending">by URI in descending order</option>
<option value="field:uri:descending">by URI in descending order</option>
</select>
</p>
</form>
EOT
} 

open PUBLIC_LISTS, "/usr/lib/mailman/bin/list_lists -b -a -V gnome.org|" || die "Cannot read list of public lists from mailman: $!\n";
my @dirs = <PUBLIC_LISTS>;
close PUBLIC_LISTS;

  open INDEX, "> $dirname/index.html" || die "Cannot open index $dirname/index.html: $!\n";

  print INDEX <<EOT;
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html>
<!-- 


     autogenerated by /home/admin/mhonarc/update-master.pl
     DO *NOT* EDIT! Run the above instead.


-->
  <head>
     <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
     <title>The mail.gnome.org Archives</title>
  </head>
  <body>
     <h1>The mail.gnome.org Archives</h1>

<p><b>NOTICE (2006-07-08):</b> We're re-building the archive search indexes (again). It bombed out silently last time leaving lockfiles in place (and archives unsearchable). Please bear with us while we try to get it sorted out. -- GNOME sysadmin team.</p>

EOT
    write_form (\@dirs);

  print INDEX <<EOT;  
    <hr/>
    <ul>
EOT
    for $dir (@dirs) {
	print INDEX <<EOT
       <li><a href="$dir/">$dir</a></li>
EOT
  }

  print INDEX <<EOT;
    </ul>
  </body>
</html>
EOT
    
close INDEX;

open INDEX, "> $NAMAZU_HEAD" || die "Cannot open index $dirname/index.html: $!\n";

print INDEX <<EOT;
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN"
        "http://www.w3.org/TR/REC-html40/strict.dtd">
<html>
<!--

     autogenerated by /home/admin/mhonarc/update-master.pl
     DO *NOT* EDIT! Run the above instead.

-->
<head>
<!-- LINK-REV-MADE -->
<link rev=made href="mailto:support\@gnome.org">
<!-- LINK-REV-MADE -->
<title>Search mail.gnome.org</title>
<style type="text/css"><!--
  strong.keyword { color: Red; }
  p.example      { text-indent: 1em; 
                   color: Navy;
		   font-weight: bold;
                   font-family: monospace; }
  code           { color: Navy;
                   font-family: monospace; }
  code.example   { color: Navy;
		   font-weight: bold;
                   font-family: monospace; }
  code.operator  { color: Navy;
                   font-family: monospace; 
		   font-weight: bold; }
--></style>
</head>
<body>
<h1>Search mail.gnome.org</h1>

<p><b>NOTICE (2006-07-08):</b> We're re-building the archive search indexes (again). It bombed out silently last time leaving lockfiles in place (and archives unsearchable). Please bear with us while we try to get it sorted out. -- GNOME sysadmin team.</p>

<p>
This index contains <!-- FILE --> lots of <!-- FILE --> documents and
<!-- KEY --> lots of <!-- KEY --> keywords. 
</p>
<p>
<strong>Last modified: <!-- DATE --> 2006-07-08 <!-- DATE --></strong>
</p>
<hr/>
EOT

write_form (\@dirs);
close INDEX;
